Feat/5 resume upload
scrum-gang/jobhub-web pull request #76
Opened 2019-03-24 16:32 UTC by sulemanmalik

closes #61, #63 and #64 
#62 (closed by andrei)

2019-03-24 17:03 UTC, AndreiUngur approved these changes
Great job! I have some nitpick comments, please address them if you can, if not they're not "deal breakers" so long as our linting tool doesn't complain too much.

2019-03-24 17:03 UTC, AndreiUngur commented on src/Features/ResumeUpload/Upload.tsx
> +      // console.log("posted: ", postedResume)
Remove console logs

2019-03-24 17:03 UTC, AndreiUngur commented on src/Features/ResumeUpload/Upload.tsx
> +                  {/* <div style={{ float: "left", paddingTop: "20px" }}>
Remove commented code

2019-03-24 17:03 UTC, AndreiUngur commented on src/Features/ResumeUpload/Upload.tsx
> +              // handleBase64Encoding(items[0].file).then(data => console.log(data.toString().split(",")[1]))
Remove comments

2019-03-24 17:04 UTC, alexboii requested changes
mostly looks good, great job boii 

I left some minor comments that I suggest to check out 

however, I think there are three very important things missing: 

- form validations
- **validating that the file is not bigger than a certain size**
- set a loader for the base64 encoder and conditionally render it (because it might take some time to encode a file)

2019-03-24 17:04 UTC, alexboii commented on package.json
> +    "file-base64": "^1.0.0",
are all of these imports used?

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +  // const [resumes, setResumes] = useState<IFile[]>([]);
remove comment

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +    if (userInfo) {
this clause already in `fetchResumes`

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +      const result = (await resumesAPI.getResumesUser(userInfo._id)).data;
surround with try/catch and toast

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +      await resumesAPI.deleteResumeUser(
surround with try/catch and toast

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +      // console.log("posted: ", postedResume)
remove comments

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +    const b64d = await handleBase64Encoding(file.file).then(data => data.toString().split(",")[1])
this is fine, but for the future consider not mixing promises and async/await in such a way, it looks a bit awkward imo 

I think you could just do 

```
const result = (await handleBase64Encoding(file.file)).toString(split(",")[1]);
```

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +      await resumesAPI.createResumeUser(postedResume);
surround with try/catch and toast

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +        await resumesAPI.patchResumeRevision(resumeToPatchId, payload);
surround with try/catch and toast

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +                  {/* <div style={{ float: "left", paddingTop: "20px" }}>
remove comment

2019-03-24 17:04 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +              // handleBase64Encoding(items[0].file).then(data => console.log(data.toString().split(",")[1]))
remove comment

2019-03-24 17:04 UTC, alexboii commented on src/api/resumesAPI.ts
> +  GET_RESUMES = "/resumes",
maybe extract into one constant? I don't know, what do you think @erickzhao @AndreiUngur

2019-03-24 17:13 UTC, eliashomsi approved these changes
This looks good to me :). Thanks @sulemanmalik for being such an awesome dude

2019-03-24 18:44 UTC, sulemanmalik commented on src/Features/ResumeUpload/Upload.tsx
> +    const b64d = await handleBase64Encoding(file.file).then(data => data.toString().split(",")[1])
Tried this and it didn't work. Only seems to work when I use await and promises

2019-03-24 18:45 UTC, sulemanmalik commented on src/Features/ResumeUpload/Upload.tsx
> +      await resumesAPI.createResumeUser(postedResume);
Surrounded all other async calls with try/catch and toast. Only this one is giving trouble because it gives a 500 error and then posts it fine with a 200 status. So I the toast error but it uploads fine. Any idea how to fix?

2019-03-24 19:17 UTC, alexboii commented on src/Features/ResumeUpload/Upload.tsx
> +      await resumesAPI.createResumeUser(postedResume);
why does it give an error 500? that sounds like something on @ealhomsi's end, interal server error or something, check it out with him

2019-03-24 19:24 UTC, erickzhao commented on src/api/resumesAPI.ts
> +  GET_RESUMES = "/resumes",
yeah probably lol `/resumes` could just be one

2019-03-24 19:25 UTC, sulemanmalik commented on src/Features/ResumeUpload/Upload.tsx
> +      await resumesAPI.createResumeUser(postedResume);
Left it without the try catch for now, will fix later if time permits

2019-03-24 22:26 UTC, sulemanmalik commented on src/Features/ResumeUpload/Upload.tsx
> +      await resumesAPI.createResumeUser(postedResume);
resolved using custom uploader

2019-03-25 01:31 UTC, alexboii approved these changes

2019-03-25 01:53 UTC, merged